using System.Text.Json.Nodes;
using Koz.Application.Customers;
using Npgsql;
namespace Koz.Infrastructure.Customers;
public sealed class PostgresCustomerMutationRepository(NpgsqlDataSource data):ICustomerMutationRepository
{
 const string Profile="jsonb_build_object('user',jsonb_build_object('id',u.id,'name',u.name,'phone',u.phone,'email',u.email),'customer',jsonb_build_object('id',c.id,'user_id',c.user_id,'store_id',c.store_id,'name',c.name,'phone',c.phone,'email',c.email,'subscription_status',c.subscription_status,'subscription_start_date',c.subscription_start_date,'subscription_end_date',c.subscription_end_date,'subscription_auto_renew',c.subscription_auto_renew),'subscription_status',c.subscription_status,'subscription_start_date',c.subscription_start_date,'subscription_end_date',c.subscription_end_date,'subscription_auto_renew',c.subscription_auto_renew)::text";
 public async Task<JsonObject> UpdateProfileAsync(string user,JsonObject body,CancellationToken ct){var id=Guid.Parse(user);var name=body.ContainsKey("name")?(body["name"]?.GetValue<string>()?.Trim()):null;var email=body.ContainsKey("email")?(body["email"]?.GetValue<string>()?.Trim()):null;await using var c=await data.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);try{if(body.ContainsKey("name")||body.ContainsKey("email")){await Exec(c,t,"UPDATE users SET name=CASE WHEN $2 THEN $3 ELSE name END,email=CASE WHEN $4 THEN $5 ELSE email END,updated_at=NOW() WHERE id=$1",ct,id,body.ContainsKey("name"),name,body.ContainsKey("email"),string.IsNullOrEmpty(email)?null:email);await Exec(c,t,"UPDATE customers SET name=CASE WHEN $2 THEN $3 ELSE name END,email=CASE WHEN $4 THEN $5 ELSE email END,updated_at=NOW() WHERE user_id=$1",ct,id,body.ContainsKey("name"),name,body.ContainsKey("email"),string.IsNullOrEmpty(email)?null:email);}var p=await One(c,t,$"SELECT {Profile} FROM users u JOIN customers c ON c.user_id=u.id WHERE u.id=$1",ct,id);if(p.Count==0)throw E(404,"Customer profile was not found","profile_not_found");await t.CommitAsync(ct);return new(){["profile"]=p};}catch{await t.RollbackAsync(CancellationToken.None);throw;}}
 public async Task<JsonObject> CreateAddressAsync(string user,JsonObject b,CancellationToken ct){if(b["store_coverage_id"]?.GetValue<string>() is not string coverage||!Guid.TryParse(coverage,out var coverageId))throw E(400,"store_coverage_id is required","store_coverage_id_required"); foreach(var n in new[]{"entrance","floor","apartment"})if(b[n] is JsonValue v&&v.TryGetValue<object>(out var x)&&x is not null&&!int.TryParse(x.ToString(),out _))throw E(400,$"{n} must be an integer number",$"invalid_{n}");await using var c=await data.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);try{var context=await One(c,t,"SELECT jsonb_build_object('id',c.id,'store_id',c.store_id,'coverage_store_id',sc.store_id,'active',sc.active,'entrance_count',sc.entrance_count,'address',sc.address)::text FROM customers c LEFT JOIN store_coverage sc ON sc.id=$2 WHERE c.user_id=$1",ct,Guid.Parse(user),coverageId);if(context.Count==0)throw E(404,"Customer user was not found","customer_user_not_found");if(context["coverage_store_id"] is null)throw E(404,"Store coverage was not found","store_coverage_not_found");if(!context["active"]!.GetValue<bool>())throw E(400,"Store coverage is not active","store_coverage_inactive");if(context["store_id"]!.GetValue<string>()!=context["coverage_store_id"]!.GetValue<string>())throw E(403,"Store coverage does not belong to the customer store","store_coverage_store_mismatch");var entrance=I(b,"entrance");if(entrance is not null&&context["entrance_count"] is JsonValue e&&e.TryGetValue<int>(out var max)&&entrance>max)throw E(400,"entrance cannot exceed coverage entrance_count","entrance_exceeds_coverage");if(b["is_default"]?.GetValue<bool>()==true)await Exec(c,t,"UPDATE customer_addresses SET is_default=FALSE WHERE customer_id=$1",ct,Guid.Parse(context["id"]!.GetValue<string>()));var a=await One(c,t,"WITH i AS (INSERT INTO customer_addresses(customer_id,store_coverage_id,entrance,floor,apartment,entrance_code,is_default) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *) SELECT jsonb_build_object('id',i.id,'customer_record_id',i.customer_id,'store_coverage_id',i.store_coverage_id,'entrance',i.entrance,'floor',i.floor,'apartment',i.apartment,'entrance_code',i.entrance_code,'is_default',i.is_default,'created_at',i.created_at,'store_id',$8::uuid,'coverage_address',$9,'entrance_count',$10)::text FROM i",ct,Guid.Parse(context["id"]!.GetValue<string>()),coverageId,entrance,I(b,"floor"),I(b,"apartment"),b["entrance_code"]?.GetValue<string>(),b["is_default"]?.GetValue<bool>()==true,Guid.Parse(context["coverage_store_id"]!.GetValue<string>()),context["address"]!.GetValue<string>(),context["entrance_count"]?.GetValue<int>());await t.CommitAsync(ct);return new(){["message"]="Address created successfully",["address"]=a};}catch{await t.RollbackAsync(CancellationToken.None);throw;}}
 public async Task<JsonObject> DeleteAddressAsync(string user,string address,CancellationToken ct){await using var c=await data.OpenConnectionAsync(ct);var n=await Exec(c,null,"DELETE FROM customer_addresses a USING customers c WHERE a.id=$1 AND a.customer_id=c.id AND c.user_id=$2",ct,Guid.Parse(address),Guid.Parse(user));if(n==0)throw E(404,"Address was not found","address_not_found");return new(){["message"]="Address deleted successfully"};}
 static int? I(JsonObject b,string n)=>b[n] is null?null:b[n]!.GetValue<int>();static CustomerMutationContractException E(int s,string m,string c)=>new(s,m,c);static async Task<JsonObject> One(NpgsqlConnection c,NpgsqlTransaction? t,string s,CancellationToken ct,params object?[] v){await using var q=new NpgsqlCommand(s,c,t);foreach(var x in v)q.Parameters.AddWithValue(x??DBNull.Value);return (await q.ExecuteScalarAsync(ct) as string) is string z?JsonNode.Parse(z)!.AsObject():new();}static async Task<int> Exec(NpgsqlConnection c,NpgsqlTransaction? t,string s,CancellationToken ct,params object?[] v){await using var q=new NpgsqlCommand(s,c,t);foreach(var x in v)q.Parameters.AddWithValue(x??DBNull.Value);return await q.ExecuteNonQueryAsync(ct);}
}
