<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Koz.Application\Koz.Application.csproj" />
    <ProjectReference Include="..\Koz.Domain\Koz.Domain.csproj" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
  </ItemGroup>
</Project>
