using System.Globalization; using System.Text.Json;
namespace Koz.Application.Orders;
public sealed class ManagerInventoryService(IManagerInventoryRepository repository)
{
 public Task<ManagerInventoryResponse> ListAsync(string? store,CancellationToken ct)=>Wrap(repository.InventoryAsync(Store(store),ct));
 public Task<ManagerInventoryItemResponse> UpdateAsync(string? store,string id,ManagerInventoryUpdateRequest r,CancellationToken ct){Validate(r);return WrapItem(repository.UpdateInventoryAsync(Store(store),id,r,ct));}
 public Task<ManagerInventoryItemResponse> ReceiveAsync(string? store,string id,JsonElement q,CancellationToken ct){var n=Number(q);if(n<=0)throw new ManagerOrderContractException(400,"quantity must be greater than 0","invalid_inventory_quantity");return WrapItem(repository.ReceiveAsync(Store(store),id,n,ct));}
 public Task<ManagerAnalyticsResponse> AnalyticsAsync(string? store,string? from,string? to,CancellationToken ct){var today=DateOnly.FromDateTime(DateTime.UtcNow).ToString("yyyy-MM-dd",CultureInfo.InvariantCulture);return WrapAnalytics(repository.AnalyticsAsync(Store(store),from??today,to??today,ct));}
 static string Store(string? s)=>string.IsNullOrEmpty(s)?throw new ManagerOrderContractException(403,"Store operator store_id is required","store_scope_required"):s;
 static decimal Number(JsonElement e)=>e.ValueKind switch{JsonValueKind.Number when e.TryGetDecimal(out var n)=>n,JsonValueKind.String when decimal.TryParse(e.GetString(),NumberStyles.Float,CultureInfo.InvariantCulture,out var n)=>n,_=>decimal.MinValue};
 static void Validate(ManagerInventoryUpdateRequest r){var any=r.IsVisible.ValueKind!=JsonValueKind.Undefined||r.SellingPrice.ValueKind!=JsonValueKind.Undefined||r.Quantity.ValueKind!=JsonValueKind.Undefined;if(!any)throw new ManagerOrderContractException(400,"No inventory fields provided","inventory_update_required");if(r.IsVisible.ValueKind!=JsonValueKind.Undefined&&r.IsVisible.ValueKind is not JsonValueKind.True and not JsonValueKind.False)throw new ManagerOrderContractException(400,"is_visible must be boolean","invalid_inventory_visibility");var p=Number(r.SellingPrice);if(r.SellingPrice.ValueKind!=JsonValueKind.Undefined&&r.SellingPrice.ValueKind!=JsonValueKind.Null&&(p<0||p==decimal.MinValue))throw new ManagerOrderContractException(400,"selling_price must be null or non-negative","invalid_selling_price");var q=Number(r.Quantity);if(r.Quantity.ValueKind!=JsonValueKind.Undefined&&(q<0||q==decimal.MinValue))throw new ManagerOrderContractException(400,"quantity must be greater than or equal to 0","invalid_inventory_quantity");}
 static async Task<ManagerInventoryResponse> Wrap(Task<IReadOnlyList<ManagerInventoryDto>> t)=>new(await t);static async Task<ManagerInventoryItemResponse> WrapItem(Task<ManagerInventoryDto>t)=>new(await t);static async Task<ManagerAnalyticsResponse> WrapAnalytics(Task<ManagerAnalyticsDto>t)=>new(await t);
}
