using System.Text.Json;
using System.Text.Json.Nodes;
using Koz.Application.AdminCatalog;
using Npgsql;
namespace Koz.Infrastructure.AdminCatalog;
public sealed class PostgresAdminCatalogRepository(NpgsqlDataSource data):IAdminCatalogRepository
{
 private const string StoreJson="json_build_object('id',id,'name',name,'address',address,'location',location,'operating_hours',operating_hours,'delivery_time_min',delivery_time_min,'delivery_time_max',delivery_time_max,'status',status,'created_at',to_char(created_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'),'updated_at',to_char(updated_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'))::text";
 private const string ProductJson="json_build_object('id',id,'name',name,'category',category,'unit',unit,'price_per_unit',price_per_unit::text,'company_price',company_price::text,'is_weighted',is_weighted,'is_active',is_active,'created_at',to_char(created_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'),'updated_at',to_char(updated_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'))::text";
 private const string InventoryJson="json_build_object('id',id,'store_id',store_id,'product_id',product_id,'quantity',quantity::text,'stock_quantity',stock_quantity,'selling_price',selling_price::text,'is_visible',is_visible,'status',status,'last_delivery_date',CASE WHEN last_delivery_date IS NULL THEN NULL ELSE to_char(last_delivery_date::timestamp - interval '5 hours','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"') END,'created_at',to_char(created_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'),'updated_at',to_char(updated_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'))::text";
 private const string PromoJson="json_build_object('id',id,'store_id',store_id,'code',code,'discount_type',discount_type,'discount_value',discount_value::text,'min_order_value',min_order_value::text,'max_uses',max_uses,'usage_per_customer',usage_per_customer,'valid_from',CASE WHEN valid_from IS NULL THEN NULL ELSE to_char(valid_from AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"') END,'valid_until',CASE WHEN valid_until IS NULL THEN NULL ELSE to_char(valid_until AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"') END,'is_active',is_active,'created_at',to_char(created_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'),'updated_at',to_char(updated_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'))::text";
 public async Task<JsonObject> ListStoresAsync(CancellationToken ct)=>new(){["stores"]=await Array("SELECT COALESCE(json_agg(x ORDER BY created_at DESC),'[]')::text FROM (SELECT json_build_object('id',s.id,'name',s.name,'address',s.address,'location',s.location,'operating_hours',s.operating_hours,'delivery_time_min',s.delivery_time_min,'delivery_time_max',s.delivery_time_max,'status',s.status,'created_at',to_char(s.created_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'),'updated_at',to_char(s.updated_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'),'delivery_settings',CASE WHEN ds.id IS NULL THEN NULL ELSE json_build_object('id',ds.id,'store_id',ds.store_id,'min_order_value_for_free_delivery',ds.min_order_value_for_free_delivery::float8,'delivery_fee',ds.delivery_fee::float8,'ordering_open_hour',ds.ordering_open_hour,'ordering_close_hour',ds.ordering_close_hour,'created_at',ds.created_at,'updated_at',ds.updated_at) END,'coverage_count',COUNT(DISTINCT sc.id)::int,'subscribers_count',COUNT(DISTINCT c.id)::int) x,s.created_at FROM stores s LEFT JOIN delivery_settings ds ON ds.store_id=s.id LEFT JOIN store_coverage sc ON sc.store_id=s.id AND sc.active=TRUE LEFT JOIN customers c ON c.store_id=s.id AND c.subscription_status='active' GROUP BY s.id,ds.id)x",ct)};
 public async Task<JsonObject> CreateStoreAsync(AdminCatalogStoreRequest x,CancellationToken ct){await using var c=await data.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);try{var o=await One(c,t,$"INSERT INTO stores(name,address,location,operating_hours,delivery_time_min,delivery_time_max,status) VALUES($1,$2,$3,$4,$5,$6,$7::store_status) RETURNING {StoreJson}",ct,x.Name!.Trim(),x.Address!.Trim(),x.Location,x.OperatingHours,x.DeliveryTimeMin,x.DeliveryTimeMax,x.Status??"active");var id=o["id"]!.GetValue<string>();await Exec(c,t,"INSERT INTO delivery_settings(store_id,min_order_value_for_free_delivery,delivery_fee,ordering_open_hour,ordering_close_hour) VALUES($1,5000,500,11,20)",ct,Guid.Parse(id));await t.CommitAsync(ct);return new(){["store"]=o};}catch{await t.RollbackAsync(CancellationToken.None);throw;}}
 public async Task<JsonObject> UpdateStoreAsync(string id,AdminCatalogStoreRequest x,CancellationToken ct)=>new(){["store"]=await ExistingSql($"UPDATE stores SET name=COALESCE($2,name),address=COALESCE($3,address),location=COALESCE($4,location),operating_hours=COALESCE($5,operating_hours),delivery_time_min=COALESCE($6,delivery_time_min),delivery_time_max=COALESCE($7,delivery_time_max),status=COALESCE($8::store_status,status),updated_at=NOW() WHERE id=$1 RETURNING {StoreJson}",id,"store_not_found",ct,x.Name,x.Address,x.Location,x.OperatingHours,x.DeliveryTimeMin,x.DeliveryTimeMax,x.Status)};
 public async Task<JsonObject> DeleteStoreAsync(string id,CancellationToken ct)=>new(){["store"]=await ExistingSql($"UPDATE stores SET status='inactive',updated_at=NOW() WHERE id=$1 RETURNING {StoreJson}",id,"store_not_found",ct)};
 public async Task<JsonObject> UpsertCoverageAsync(AdminCatalogCoverageRequest x,CancellationToken ct){var store=Guid.Parse(x.StoreId!);var address=x.Address!.Trim();var response=await One("INSERT INTO store_coverage(store_id,address,entrance_count,active) VALUES($1,$2,$3,TRUE) ON CONFLICT(store_id,address) DO UPDATE SET entrance_count=EXCLUDED.entrance_count,active=TRUE,updated_at=NOW() RETURNING json_build_object('__created',(xmax=0),'id',id,'store_id',store_id,'address',address,'entrance_count',entrance_count,'active',active,'created_at',to_char(created_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'),'updated_at',to_char(updated_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'))::text",ct,store,address,x.EntranceCount);var created=response["__created"]!.GetValue<bool>();response.Remove("__created");return new(){["coverage"]=response,["__created"]=created};}
 public async Task<JsonObject> ListProductsAsync(CancellationToken ct)=>new(){["products"]=await Array("SELECT COALESCE(json_agg(json_build_object('id',id,'name',name,'category',category,'unit',unit,'price_per_unit',price_per_unit::text,'company_price',company_price::text,'is_weighted',is_weighted,'is_active',is_active,'created_at',to_char(created_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'),'updated_at',to_char(updated_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"')) ORDER BY created_at DESC),'[]')::text FROM products",ct)};
 public async Task<JsonObject> CreateProductAsync(AdminCatalogProductRequest x,CancellationToken ct)=>new(){["product"]=await Product($"INSERT INTO products(name,category,unit,price_per_unit,company_price,is_weighted,is_active) VALUES($1,$2::product_category,$3::product_unit,$4,$5,$6,$7) RETURNING {ProductJson}",null,x,ct)};
 public async Task<JsonObject> UpdateProductAsync(string id,AdminCatalogProductRequest x,CancellationToken ct)=>new(){["product"]=await Product($"UPDATE products SET name=COALESCE($2,name),category=COALESCE($3::product_category,category),unit=COALESCE($4::product_unit,unit),price_per_unit=COALESCE($5,price_per_unit),company_price=COALESCE($6,company_price),is_weighted=COALESCE($7,is_weighted),is_active=COALESCE($8,is_active),updated_at=NOW() WHERE id=$1 RETURNING {ProductJson}",id,x,ct)};
 public async Task<JsonObject> DeleteProductAsync(string id,CancellationToken ct)=>new(){["product"]=await ExistingSql($"UPDATE products SET is_active=FALSE,updated_at=NOW() WHERE id=$1 RETURNING {ProductJson}",id,"product_not_found",ct)};
 private async Task<JsonObject> Product(string sql,string? id,AdminCatalogProductRequest x,CancellationToken ct){try{var o=await One(sql,ct,id is null?new object?[]{x.Name?.Trim(),x.Category,x.Unit,Decimal(x.PricePerUnit),Decimal(x.CompanyPrice),Bool(x.IsWeighted),x.IsActive.ValueKind==JsonValueKind.Undefined?true:Bool(x.IsActive)}:new object?[]{Guid.Parse(id),x.Name?.Trim(),x.Category,x.Unit,Decimal(x.PricePerUnit),Decimal(x.CompanyPrice),NullableBool(x.IsWeighted),NullableBool(x.IsActive)});if(o.Count==0)throw E(404,"product_not_found was not found","product_not_found");return o;}catch(PostgresException e)when(e.SqlState=="23505"){throw E(409,"Entity already exists","duplicate_entity");}}
 private static decimal? Decimal(JsonElement x)=>x.ValueKind==JsonValueKind.Undefined?null:x.ValueKind==JsonValueKind.Number?x.GetDecimal():decimal.Parse(x.GetString()!);private static bool Bool(JsonElement x)=>x.GetBoolean();private static bool? NullableBool(JsonElement x)=>x.ValueKind==JsonValueKind.Undefined?null:x.GetBoolean();
 public async Task<JsonObject> ListInventoryAsync(string store,CancellationToken ct)=>new(){["inventory"]=await Array("SELECT COALESCE(json_agg(json_build_object('id',id,'store_id',store_id,'product_id',product_id,'name',name,'category',category,'unit',unit,'is_weighted',is_weighted,'price_per_unit',price_per_unit::text,'company_price',company_price::text,'selling_price',selling_price::text,'effective_price',effective_price::text,'quantity',quantity::text,'stock_quantity',stock_quantity,'is_visible',is_visible,'status',status,'last_delivery_date',CASE WHEN last_delivery_date IS NULL THEN NULL ELSE to_char(last_delivery_date::timestamp - interval '5 hours','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"') END) ORDER BY category,name),'[]')::text FROM (SELECT si.id,si.store_id,si.product_id,p.name,p.category,p.unit,p.is_weighted,p.price_per_unit,p.company_price,si.selling_price,COALESCE(si.selling_price,p.price_per_unit) effective_price,si.quantity,si.stock_quantity,si.is_visible,si.status,si.last_delivery_date FROM store_inventory si JOIN products p ON p.id=si.product_id WHERE si.store_id=$1)x",ct,Guid.Parse(store))};
 public async Task<JsonObject> UpsertInventoryAsync(string store,string product,AdminCatalogInventoryRequest x,CancellationToken ct){var q=Decimal(x.Quantity)??0;var sp=x.SellingPrice.ValueKind is JsonValueKind.Undefined or JsonValueKind.Null?null:Decimal(x.SellingPrice);var vis=x.IsVisible.ValueKind==JsonValueKind.Undefined||Bool(x.IsVisible);var o=await One($"INSERT INTO store_inventory(store_id,product_id,selling_price,quantity,stock_quantity,is_visible,status) VALUES($1,$2,$3,$4,CEIL($4)::int,$5,(CASE WHEN $4<=0 THEN 'out_of_stock' WHEN $4<=2 THEN 'low_stock' ELSE 'available' END)::inventory_status) ON CONFLICT(store_id,product_id) DO UPDATE SET selling_price=EXCLUDED.selling_price,quantity=EXCLUDED.quantity,stock_quantity=EXCLUDED.stock_quantity,is_visible=EXCLUDED.is_visible,status=EXCLUDED.status,updated_at=NOW() RETURNING {InventoryJson}",ct,Guid.Parse(store),Guid.Parse(product),sp,q,vis);return new(){["inventory"]=o};}
 public async Task<JsonObject> ReceiveInventoryAsync(string store,string product,JsonElement x,CancellationToken ct){var q=Decimal(x)??0;if(q<=0)throw E(400,"quantity must be greater than 0","invalid_inventory_quantity");return new(){["inventory"]=await ExistingSql($"UPDATE store_inventory SET quantity=quantity+$3,stock_quantity=stock_quantity+CEIL($3)::int,status='available',last_delivery_date=NOW(),updated_at=NOW() WHERE store_id=$1 AND product_id=$2 RETURNING {InventoryJson}",store+":"+product,"inventory_not_found",ct,q)};}
 public async Task<JsonObject> ListPromosAsync(CancellationToken ct)=>new(){["promo_codes"]=await Array($"SELECT COALESCE(json_agg({PromoJson}::json ORDER BY created_at DESC),'[]')::text FROM promo_codes",ct)};
 public async Task<JsonObject> CreatePromoAsync(AdminCatalogPromoRequest x,CancellationToken ct)=>new(){["promo_code"]=await Promo($"INSERT INTO promo_codes(store_id,code,discount_type,discount_value,min_order_value,max_uses,usage_per_customer,valid_from,valid_until,is_active) VALUES($1,upper($2),$3::discount_type,$4,$5,$6,$7,$8,$9,$10) RETURNING {PromoJson}",null,x,ct)};
 public async Task<JsonObject> UpdatePromoAsync(string id,AdminCatalogPromoRequest x,CancellationToken ct)=>new(){["promo_code"]=await Promo($"UPDATE promo_codes SET code=COALESCE(upper($2),code),discount_type=COALESCE($3::discount_type,discount_type),discount_value=COALESCE($4,discount_value),store_id=COALESCE($5,store_id),min_order_value=COALESCE($6,min_order_value),max_uses=COALESCE($7,max_uses),usage_per_customer=COALESCE($8,usage_per_customer),valid_from=COALESCE($9,valid_from),valid_until=COALESCE($10,valid_until),is_active=COALESCE($11,is_active),updated_at=NOW() WHERE id=$1 RETURNING {PromoJson}",id,x,ct)};
 public async Task<JsonObject> DeletePromoAsync(string id,CancellationToken ct)=>new(){["promo_code"]=await ExistingSql($"UPDATE promo_codes SET is_active=FALSE,updated_at=NOW() WHERE id=$1 RETURNING {PromoJson}",id,"promo_code_not_found",ct)};
 private async Task<JsonObject> Promo(string sql,string? id,AdminCatalogPromoRequest x,CancellationToken ct){try{var values=id is null?new object?[]{Uuid(x.StoreId),x.Code?.Trim(),x.DiscountType,Decimal(x.DiscountValue),Decimal(x.MinOrderValue)??0,Int(x.MaxUses),Int(x.UsagePerCustomer)??1,Text(x.ValidFrom),Text(x.ValidUntil),x.IsActive.ValueKind==JsonValueKind.Undefined?true:Bool(x.IsActive)}:new object?[]{Guid.Parse(id),x.Code?.Trim(),x.DiscountType,Decimal(x.DiscountValue),Uuid(x.StoreId),Decimal(x.MinOrderValue),Int(x.MaxUses),Int(x.UsagePerCustomer),Text(x.ValidFrom),Text(x.ValidUntil),NullableBool(x.IsActive)};var o=await One(sql,ct,values);if(o.Count==0)throw E(404,"promo_code_not_found was not found","promo_code_not_found");return o;}catch(PostgresException e)when(e.SqlState=="23505"){throw E(409,"Entity already exists","duplicate_entity");}}
 public async Task<JsonObject> GetDeliveryAsync(string store,CancellationToken ct)=>new(){["delivery_settings"]=await ExistingSql("SELECT json_build_object('id',id,'store_id',store_id,'min_order_value_for_free_delivery',min_order_value_for_free_delivery::text,'delivery_fee',delivery_fee::text,'ordering_open_hour',ordering_open_hour,'ordering_close_hour',ordering_close_hour,'created_at',to_char(created_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'),'updated_at',to_char(updated_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'))::text FROM delivery_settings WHERE store_id=$1",store,"delivery_settings_not_found",ct)};
 public async Task<JsonObject> UpsertDeliveryAsync(string store,AdminCatalogDeliveryRequest x,CancellationToken ct){var o=await One("INSERT INTO delivery_settings(store_id,min_order_value_for_free_delivery,delivery_fee,ordering_open_hour,ordering_close_hour) VALUES($1,COALESCE($2,5000),COALESCE($3,500),COALESCE($4,11),COALESCE($5,20)) ON CONFLICT(store_id) DO UPDATE SET min_order_value_for_free_delivery=COALESCE($2,delivery_settings.min_order_value_for_free_delivery),delivery_fee=COALESCE($3,delivery_settings.delivery_fee),ordering_open_hour=COALESCE($4,delivery_settings.ordering_open_hour),ordering_close_hour=COALESCE($5,delivery_settings.ordering_close_hour),updated_at=NOW() RETURNING json_build_object('id',id,'store_id',store_id,'min_order_value_for_free_delivery',min_order_value_for_free_delivery::text,'delivery_fee',delivery_fee::text,'ordering_open_hour',ordering_open_hour,'ordering_close_hour',ordering_close_hour,'created_at',to_char(created_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'),'updated_at',to_char(updated_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'))::text",ct,Guid.Parse(store),Decimal(x.Minimum),Decimal(x.Fee),Int(x.OpenHour),Int(x.CloseHour));return new(){["delivery_settings"]=o};}
 private async Task<JsonObject> Existing(string table,string id,Dictionary<string,object?> fields,string code,CancellationToken ct){var set=new List<string>();var v=new List<object?>{Guid.Parse(id)};foreach(var x in fields)if(x.Value is not null){v.Add(x.Value);set.Add($"{x.Key}=${v.Count}");}var sql=set.Count==0?$"SELECT to_jsonb({table})::text FROM {table} WHERE id=$1":$"UPDATE {table} SET {string.Join(',',set)},updated_at=NOW() WHERE id=$1 RETURNING to_jsonb({table})::text";return await ExistingSql(sql,id,code,ct,v.Skip(1).ToArray());}
 private async Task<JsonObject> ExistingSql(string sql,string id,string code,CancellationToken ct,params object?[] more){var values=id.Contains(':')?id.Split(':').Select(Guid.Parse).Cast<object?>().Concat(more).ToArray():new object?[]{Guid.Parse(id)}.Concat(more).ToArray();var o=await One(sql,ct,values);if(o.Count==0)throw E(404,$"{code} was not found",code);return o;}
 private async Task<JsonObject> One(string sql,CancellationToken ct,params object?[] values){await using var c=await data.OpenConnectionAsync(ct);return await One(c,null,sql,ct,values);}private static async Task<JsonObject> One(NpgsqlConnection c,NpgsqlTransaction? t,string sql,CancellationToken ct,params object?[] values){await using var q=Cmd(c,t,sql,values);var text=await q.ExecuteScalarAsync(ct) as string;return text is null?new JsonObject():JsonNode.Parse(text)!.AsObject();}private async Task<JsonArray> Array(string sql,CancellationToken ct,params object?[] values){await using var c=await data.OpenConnectionAsync(ct);await using var q=Cmd(c,null,sql,values);var text=await q.ExecuteScalarAsync(ct) as string;return text is null?new JsonArray():JsonNode.Parse(text)!.AsArray();}private static async Task Exec(NpgsqlConnection c,NpgsqlTransaction t,string sql,CancellationToken ct,params object?[] values){await using var q=Cmd(c,t,sql,values);await q.ExecuteNonQueryAsync(ct);}private static NpgsqlCommand Cmd(NpgsqlConnection c,NpgsqlTransaction? t,string sql,params object?[] values){var q=new NpgsqlCommand(sql,c,t);foreach(var x in values)q.Parameters.AddWithValue(x??DBNull.Value);return q;}private static Guid? Uuid(JsonElement x)=>x.ValueKind is JsonValueKind.Undefined or JsonValueKind.Null?null:Guid.Parse(x.GetString()!);private static int? Int(JsonElement x)=>x.ValueKind is JsonValueKind.Undefined or JsonValueKind.Null?null:x.GetInt32();private static string? Text(JsonElement x)=>x.ValueKind is JsonValueKind.Undefined or JsonValueKind.Null?null:x.GetString();private static AdminCatalogContractException E(int s,string m,string c)=>new(s,m,c);
}
