using System.Net;using System.Net.Http.Headers;using System.Net.Http.Json;using System.Text.Json;using Npgsql;using Xunit;using Xunit.Sdk;
namespace Koz.IntegrationTests;
[Collection("NodeApi")]public sealed class Net4cAdminCustomersIntegrationTests{
 [Fact,Trait("Category","Integration")]public async Task AdminCustomersMountedReadsAndRbacParity(){await using var x=await Scope.Open();var t=await x.Token();foreach(var p in new[]{"/api/admin/customers/customers","/api/admin/customers/customers?search=NET4C&page=1&limit=1","/api/admin/customers/subscriptions","/api/admin/customers/audit-logs/consents"})await Same(await x.Get(x.Node.Client,p,t),await x.Get(x.Dotnet,p,t));var d=await x.Get(x.Dotnet,"/api/admin/customers/customers","");Assert.Equal(HttpStatusCode.Unauthorized,d.StatusCode);}
 [Fact,Trait("Category","Integration")]public async Task AdminCustomerDetailAndSubscriptionActionsParity(){await using var x=await Scope.Open();var t=await x.Token();const string n="/api/admin/customers/customers/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",d="/api/admin/customers/customers/cccccccc-cccc-cccc-cccc-cccccccccccc";Assert.Equal((await x.Get(x.Node.Client,n,t)).StatusCode,(await x.Get(x.Dotnet,d,t)).StatusCode);foreach(var suffix in new[]{"/subscription/cancel","/subscription/renew","/subscription/pause"})Assert.Equal((await x.Put(x.Node.Client,n+suffix,new{immediate=false},t)).StatusCode,(await x.Put(x.Dotnet,d+suffix,new{immediate=false},t)).StatusCode);}
 [Fact,Trait("Category","Integration")]public async Task AdminCustomerSubscriptionConcurrencyParity(){await using var x=await Scope.Open();var t=await x.Token();const string n="/api/admin/customers/customers/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",d="/api/admin/customers/customers/cccccccc-cccc-cccc-cccc-cccccccccccc";for(var i=0;i<5;i++){var ns=await Parallel(()=>x.Put(x.Node.Client,n+"/subscription/renew",new{},t));var ds=await Parallel(()=>x.Put(x.Dotnet,d+"/subscription/renew",new{},t));Assert.Equal(ns,ds);}}
 static async Task<HttpStatusCode[]> Parallel(Func<Task<HttpResponseMessage>> send){using var b=new Barrier(2);var r=await Task.WhenAll(Enumerable.Range(0,2).Select(_=>Task.Run(async()=>{b.SignalAndWait();using var x=await send();return x.StatusCode;})));return r.Order().ToArray();}
 static async Task Same(HttpResponseMessage a,HttpResponseMessage b){Assert.Equal(a.StatusCode,b.StatusCode);Assert.Equal(await a.Content.ReadAsStringAsync(TestContext.Current.CancellationToken),await b.Content.ReadAsStringAsync(TestContext.Current.CancellationToken));}
 sealed class Scope: IAsyncDisposable{readonly Net1ApiFactory f;Scope(Net1ApiFactory f,HttpClient d,NodeAuthServer n){this.f=f;Dotnet=d;Node=n;}public HttpClient Dotnet{get;}public NodeAuthServer Node{get;}public static async Task<Scope> Open(){var cs=Environment.GetEnvironmentVariable("KOZ_NET4C_TEST_CONNECTION_STRING");if(string.IsNullOrWhiteSpace(cs))throw SkipException.ForSkip("Set KOZ_NET4C_TEST_CONNECTION_STRING.");Assert.Equal("koz_dotnet_net4c_test",new NpgsqlConnectionStringBuilder(cs).Database);var f=new Net1ApiFactory(cs);return new(f,f.CreateClient(),await NodeAuthServer.StartAsync(cs,TestContext.Current.CancellationToken));}public async Task<string> Token(){var r=await Dotnet.PostAsJsonAsync("/api/auth/staff/login",new{email="customers@koz.kz",password="Manager123"},TestContext.Current.CancellationToken);using var j=JsonDocument.Parse(await r.Content.ReadAsStringAsync(TestContext.Current.CancellationToken));return j.RootElement.GetProperty("token").GetString()!;}public Task<HttpResponseMessage> Get(HttpClient c,string p,string t){var q=new HttpRequestMessage(HttpMethod.Get,p);if(t!="")q.Headers.Authorization=new AuthenticationHeaderValue("Bearer",t);return c.SendAsync(q,TestContext.Current.CancellationToken);}public Task<HttpResponseMessage> Put(HttpClient c,string p,object b,string t){var q=new HttpRequestMessage(HttpMethod.Put,p){Content=JsonContent.Create(b)};q.Headers.Authorization=new AuthenticationHeaderValue("Bearer",t);return c.SendAsync(q,TestContext.Current.CancellationToken);}public ValueTask DisposeAsync(){Node.Dispose();Dotnet.Dispose();f.Dispose();return ValueTask.CompletedTask;}}
}
