using System.Globalization;
using Koz.Application.Commerce;
using Npgsql;
namespace Koz.Infrastructure.Commerce;
public sealed class PostgresCommerceRepository(NpgsqlDataSource ds) : ICommerceRepository
{
 public async Task<CustomerCommerce?> FindCustomerByUserIdAsync(string id,CancellationToken ct)=>await CustomerAsync("WHERE c.user_id=$1",id,ct);
 public async Task<CustomerCommerce?> FindCustomerByIdAsync(string id,CancellationToken ct)=>await CustomerAsync("WHERE c.id=$1",id,ct);
 async Task<CustomerCommerce?> CustomerAsync(string where,string id,CancellationToken ct){await using var c=await ds.OpenConnectionAsync(ct);await using var q=new NpgsqlCommand($"SELECT c.id,c.user_id,c.store_id,c.subscription_end_date,s.billing_period,s.expires_at FROM customers c LEFT JOIN LATERAL (SELECT billing_period,expires_at FROM subscriptions WHERE customer_id=c.id ORDER BY expires_at DESC NULLS LAST,created_at DESC LIMIT 1) s ON TRUE {where}",c);q.Parameters.AddWithValue(Guid.Parse(id));await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?new(r.GetGuid(0).ToString(),r.GetGuid(1).ToString(),r.GetGuid(2).ToString(),r.IsDBNull(3)?null:r.GetFieldValue<DateOnly>(3).ToString("yyyy-MM-dd",CultureInfo.InvariantCulture),r.IsDBNull(4)?null:r.GetString(4),r.IsDBNull(5)?null:r.GetFieldValue<DateTimeOffset>(5)):null;}
 public async Task<CreateSubscriptionResult> CreateSubscriptionAsync(string customer,decimal amount,string period,DateTimeOffset expires,CancellationToken ct){await using var c=await ds.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);try{await using(var a=new NpgsqlCommand("SELECT id FROM subscriptions WHERE customer_id=$1 AND status='active' AND expires_at>NOW() LIMIT 1 FOR UPDATE",c,t)){a.Parameters.AddWithValue(Guid.Parse(customer));if(await a.ExecuteScalarAsync(ct) is not null){await t.RollbackAsync(ct);return new(true,null);}} var s=await InsertAsync(c,t,customer,amount,period,expires,ct);await using(var u=new NpgsqlCommand("UPDATE customers SET subscription_status='active',subscription_start_date=CURRENT_DATE,subscription_end_date=$2::date,subscription_auto_renew=TRUE,updated_at=NOW() WHERE id=$1",c,t)){u.Parameters.AddWithValue(Guid.Parse(customer));u.Parameters.AddWithValue(expires);await u.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);return new(false,s);}catch{await t.RollbackAsync(ct);throw;}}
 public async Task<SubscriptionDto> RenewAsync(string customer,DateTimeOffset expires,string period,CancellationToken ct){await using var c=await ds.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);try{SubscriptionDto s;await using(var q=new NpgsqlCommand("SELECT id,amount FROM subscriptions WHERE customer_id=$1 ORDER BY expires_at DESC NULLS LAST,created_at DESC LIMIT 1 FOR UPDATE",c,t)){q.Parameters.AddWithValue(Guid.Parse(customer));await using var r=await q.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct)){var id=r.GetGuid(0);await r.CloseAsync();await using var u=new NpgsqlCommand("UPDATE subscriptions SET status='active',expires_at=$2,next_billing_date=$2::date,auto_renew=TRUE,cancelled_at=NULL,updated_at=NOW() WHERE id=$1 RETURNING *",c,t);u.Parameters.AddWithValue(id);u.Parameters.AddWithValue(expires);await using var rr=await u.ExecuteReaderAsync(ct);await rr.ReadAsync(ct);s=Read(rr);}else{s=await InsertAsync(c,t,customer,3900m,"monthly",expires,ct);}}await using(var u=new NpgsqlCommand("UPDATE customers SET subscription_status='active',subscription_start_date=COALESCE(subscription_start_date,CURRENT_DATE),subscription_end_date=$2::date,subscription_auto_renew=TRUE,updated_at=NOW() WHERE id=$1",c,t)){u.Parameters.AddWithValue(Guid.Parse(customer));u.Parameters.AddWithValue(expires);await u.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);return s;}catch{await t.RollbackAsync(ct);throw;}}
 public async Task<SubscriptionDto?> CancelAsync(string customer,bool immediate,CancellationToken ct){await using var c=await ds.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);try{await using var q=new NpgsqlCommand("SELECT id FROM subscriptions WHERE customer_id=$1 AND status='active' ORDER BY expires_at DESC NULLS LAST,created_at DESC LIMIT 1 FOR UPDATE",c,t);q.Parameters.AddWithValue(Guid.Parse(customer));var id=await q.ExecuteScalarAsync(ct);if(id is null){await t.RollbackAsync(ct);return null;}await using var u=new NpgsqlCommand(immediate?"UPDATE subscriptions SET status='cancelled',expires_at=NOW(),next_billing_date=NULL,auto_renew=FALSE,cancelled_at=NOW(),updated_at=NOW() WHERE id=$1 RETURNING *":"UPDATE subscriptions SET auto_renew=FALSE,cancelled_at=NOW(),updated_at=NOW() WHERE id=$1 RETURNING *",c,t);u.Parameters.AddWithValue((Guid)id);await using var r=await u.ExecuteReaderAsync(ct);await r.ReadAsync(ct);var s=Read(r);await r.CloseAsync();await using var cu=new NpgsqlCommand(immediate?"UPDATE customers SET subscription_status='cancelled',subscription_end_date=CURRENT_DATE,subscription_auto_renew=FALSE,updated_at=NOW() WHERE id=$1":"UPDATE customers SET subscription_auto_renew=FALSE,updated_at=NOW() WHERE id=$1",c,t);cu.Parameters.AddWithValue(Guid.Parse(customer));await cu.ExecuteNonQueryAsync(ct);await t.CommitAsync(ct);return s;}catch{await t.RollbackAsync(ct);throw;}}
 public async Task<IReadOnlyList<SubscriptionListDto>> ListAsync(string? store,string? status,CancellationToken ct){await using var c=await ds.OpenConnectionAsync(ct);var sql="SELECT s.*,c.name,c.phone,c.email,c.store_id FROM subscriptions s JOIN customers c ON c.id=s.customer_id";var cond=new List<string>();await using var q=new NpgsqlCommand{Connection=c};if(!string.IsNullOrEmpty(store)){q.Parameters.AddWithValue(Guid.Parse(store));cond.Add("c.store_id=$1");}if(!string.IsNullOrEmpty(status)){q.Parameters.AddWithValue(status);cond.Add($"s.status=${q.Parameters.Count}::subscription_status");}q.CommandText=$"{sql}{(cond.Count>0?" WHERE "+string.Join(" AND ",cond):string.Empty)} ORDER BY s.created_at DESC";await using var r=await q.ExecuteReaderAsync(ct);var x=new List<SubscriptionListDto>();while(await r.ReadAsync(ct)){var s=Read(r);x.Add(new(s.Id,s.CustomerId,s.Amount,s.BillingPeriod,s.Status,s.ExpiresAt,s.NextBillingDate,s.AutoRenew,s.CancelledAt,s.CreatedAt,s.UpdatedAt,ReadS(r,11),ReadS(r,12),ReadS(r,13),r.GetGuid(14).ToString()));}return x;}
 public async Task<PromoCode?> FindPromoAsync(string code,CancellationToken ct){await using var c=await ds.OpenConnectionAsync(ct);await using var q=new NpgsqlCommand("SELECT id,store_id,discount_type,discount_value,min_order_value,max_uses,usage_per_customer,valid_from,valid_until,is_active FROM promo_codes WHERE code=upper($1)",c);q.Parameters.AddWithValue(code);await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?new(r.GetGuid(0).ToString(),r.IsDBNull(1)?null:r.GetGuid(1).ToString(),r.GetString(2),r.GetDecimal(3),r.GetDecimal(4),r.IsDBNull(5)?null:r.GetInt32(5),r.GetInt32(6),r.IsDBNull(7)?null:r.GetFieldValue<DateTimeOffset>(7),r.IsDBNull(8)?null:r.GetFieldValue<DateTimeOffset>(8),r.GetBoolean(9)):null;}
 public async Task<int> CountUsesAsync(string promo,string? customer,CancellationToken ct){await using var c=await ds.OpenConnectionAsync(ct);await using var q=new NpgsqlCommand(customer is null?"SELECT COUNT(*)::int FROM promo_code_usage WHERE promo_code_id=$1":"SELECT COUNT(*)::int FROM promo_code_usage WHERE promo_code_id=$1 AND customer_id=$2",c);q.Parameters.AddWithValue(Guid.Parse(promo));if(customer is not null)q.Parameters.AddWithValue(Guid.Parse(customer));return Convert.ToInt32(await q.ExecuteScalarAsync(ct));}
 static async Task<SubscriptionDto> InsertAsync(NpgsqlConnection c,NpgsqlTransaction t,string customer,decimal amount,string period,DateTimeOffset exp,CancellationToken ct){await using var q=new NpgsqlCommand("INSERT INTO subscriptions(customer_id,amount,billing_period,status,expires_at,next_billing_date,auto_renew) VALUES($1,$2,$3::billing_period,'active',$4,$4::date,TRUE) RETURNING *",c,t);q.Parameters.AddWithValue(Guid.Parse(customer));q.Parameters.AddWithValue(amount);q.Parameters.AddWithValue(period);q.Parameters.AddWithValue(exp);await using var r=await q.ExecuteReaderAsync(ct);await r.ReadAsync(ct);return Read(r);}
 static SubscriptionDto Read(NpgsqlDataReader r,bool extra=false)=>new(r.GetGuid(0).ToString(),r.GetGuid(1).ToString(),r.GetDecimal(2).ToString("0.00",CultureInfo.InvariantCulture),r.GetString(3),r.GetString(4),r.IsDBNull(5)?null:Ts(r.GetFieldValue<DateTimeOffset>(5)),r.IsDBNull(6)?null:Ts(new DateTimeOffset(r.GetFieldValue<DateOnly>(6).ToDateTime(TimeOnly.MinValue),TimeZoneInfo.Local.GetUtcOffset(r.GetFieldValue<DateOnly>(6).ToDateTime(TimeOnly.MinValue)))),r.GetBoolean(7),r.IsDBNull(8)?null:Ts(r.GetFieldValue<DateTimeOffset>(8)),Ts(r.GetFieldValue<DateTimeOffset>(9)),Ts(r.GetFieldValue<DateTimeOffset>(10)));
 static string? ReadS(NpgsqlDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);static string Ts(DateTimeOffset v)=>v.ToUniversalTime().ToString("yyyy-MM-dd'T'HH:mm:ss.fff'Z'",CultureInfo.InvariantCulture);
}
